version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "5050:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
